/* Generated By:JavaCC: Do not edit this line. CocoRConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CocoRConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int CHAR = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"COMPILER\"",
    "\"END\"",
    "\".\"",
    "\"CHARACTERS\"",
    "\"KEYWORDS\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"..\"",
    "\"CHR\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "<LETTER>",
    "<DIGIT>",
    "<CHAR>",
  };

}
